global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'nexuscart-services'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'host.docker.internal:8888'  # config-server
          - 'host.docker.internal:8761'  # discovery-server
          - 'host.docker.internal:8080'  # api-gateway
          - 'host.docker.internal:8081'  # auth-service
          - 'host.docker.internal:8082'  # user-service
          - 'host.docker.internal:8083'  # product-service
          - 'host.docker.internal:8084'  # inventory-service
          - 'host.docker.internal:8085'  # order-service
          - 'host.docker.internal:8086'  # payment-service
          - 'host.docker.internal:8087'  # notification-service

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9092']
